# Generated by Django 5.0.6 on 2026-03-10 20:29

import apps.fields.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldentry',
            new_name='fields_fiel_crop_ty_828dad_idx',
            old_name='fields_fiel_crop_ty_8e3c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldentry',
            new_name='fields_fiel_collect_24db72_idx',
            old_name='fields_fiel_collect_3a5b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldentry',
            new_name='fields_fiel_collect_96c837_idx',
            old_name='fields_fiel_collect_2e4a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldentry',
            new_name='fields_fiel_client__4742dc_idx',
            old_name='fields_fiel_client__7f8e2a_idx',
        ),
        migrations.AlterField(
            model_name='fieldphoto',
            name='image',
            field=models.ImageField(upload_to=apps.fields.models.photo_upload_path),
        ),
    ]
