# Generated by Django 5.0.6 on 2026-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_fieldentry_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldentry',
            name='growth_stage',
            field=models.CharField(blank=True, choices=[('emergence', 'Emergence'), ('early_vegetative', 'Early Vegetative'), ('late_vegetative', 'Late Vegetative'), ('early_productive', 'Early Productive'), ('late_reproductive', 'Late Reproductive'), ('maturity', 'Maturity'), ('harvested', 'Harvested')], max_length=20),
        ),
    ]
