# Generated by Django 5.0.6 on 2026-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_alter_fieldentry_growth_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='crop_condition',
            field=models.CharField(blank=True, choices=[('permanent_wilting', 'Permanent Wilting'), ('temporary_wilting', 'Temporary Wilting'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('leached_waterlogged', 'Leeached/Waterlogged')], max_length=50),
        ),
    ]
