# Generated by Django 5.0.6 on 2026-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_fieldentry_crop_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='sector',
            field=models.CharField(blank=True, choices=[('lscfa', 'LSCFA'), ('a2', 'A2'), ('a1', 'A1'), ('sscfa', 'SSCFA'), ('or', 'OR'), ('ca', 'CA'), ('peri_urban', 'Peri urban')], max_length=20),
        ),
    ]
