# Generated by Django 5.0.6 on 2026-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_fieldentry_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='yield_tonnes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
