# Generated by Django 5.0.6 on 2026-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0008_survey_fieldentry_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldentry',
            name='crop_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('tobacco', 'Tobacco'), ('sesame', 'Sesame'), ('sorghum', 'Sorghum'), ('cotton', 'Cotton'), ('pearl_millet', 'Pearl Millet'), ('groundnut', 'Groundnut'), ('soyabean', 'Soyabean'), ('finger_millet', 'Finger millet'), ('potato', 'Potato'), ('sunflower', 'Sunflower'), ('tea', 'Tea'), ('pepper', 'Pepper'), ('roundnut', 'Roundnut'), ('sugarcane', 'Sugarcane'), ('cabbage', 'Cabbage'), ('banana', 'Banana'), ('tomato', 'Tomato'), ('sugarbean', 'Sugarbean'), ('macademia', 'Macademia'), ('bambaranuts', 'Bambaranuts'), ('cowpea', 'African Pea/Cowpea'), ('paprika', 'Paprika'), ('rice', 'Rice'), ('cassava', 'Cassava'), ('chick_pea', 'Chick Pea'), ('pigeon_pea', 'Pigeon Pea'), ('summer_wheat', 'Summer Wheat'), ('caster_beans', 'Caster Beans'), ('cocoyam', 'Cocoyam'), ('tsenza', 'Tsenza'), ('wheat', 'Wheat'), ('barley', 'Barley'), ('pea', 'Pea'), ('other', 'Other crop')], max_length=20),
        ),
    ]
