# Generated by Django 5.0.6 on 2026-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0009_alter_fieldentry_crop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fieldentry',
            name='fertiliser_used_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fieldentry',
            name='seed_used_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
