# Generated by Django 5.0.6 on 2026-03-10 20:29

import apps.mbtiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtilesfile',
            name='file',
            field=models.FileField(upload_to=apps.mbtiles.models.mbtiles_upload_path),
        ),
    ]
