# Generated by Django 5.0.6 on 2026-03-31 03:17

import apps.mbtiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiles', '0002_alter_mbtilesfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(upload_to=apps.mbtiles.models.overlay_upload_path)),
                ('geojson_file', models.FileField(blank=True, upload_to='overlays/geojson/')),
                ('file_format', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('feature_count', models.IntegerField(default=0)),
                ('bounds', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlay_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
